spring:
  application:
    name: library

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/library}
    username: ${DATABASE_USERNAME:library}
    password: ${DATABASE_PASSWORD:library}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
